#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  rebuild)
    if [[ -z $2 ]]; then
      echo "Please specify an app to rebuild"
      exit 1
    fi
    APP="$2"
    REPO="$DOKKU_ROOT/$APP"
    REF=$(cat $REPO/refs/heads/master)
    pluginhook pre-rebuild $APP
    cd $REPO && git archive $REF | dokku receive $APP | sed -u "s/^/"$'\e[1G'"/"
    ;;

  rebuild:linked)
    for app in $(ls -d $DOKKU_ROOT/*/); do
        APP=$(basename $app)
        REPO="$DOKKU_ROOT/$APP"
        ENV_FILE="$DOKKU_ROOT/$APP/ENV"

        if grep -q "export REDIS_URL" $ENV_FILE ; then
                # This will just grep the running instance of all redis server name
                DB=$(docker ps | grep redis | awk '{print $2}' | sed -e 's/redis\///' -e 's/\:latest//')
                dokku redis:link $APP $DB
                dokku rebuild $APP
        fi
    done
    ;;

  rebuild:all)
    for app in $(ls -d $DOKKU_ROOT/*/); do
      APP=$(basename $app);
      dokku rebuild $APP
    done
    ;;

  help)
    cat && cat<<EOF
    rebuild <app>                                   Rebuild an app
    rebuild:all                                     Rebuild all apps
    rebuild:linked                                  Rebuild all apps with links(single instance of redis)
EOF
  ;;

esac

